### ISSUE TITLE
CircleCI

### ISSUE THREAD

**Issue by eggzilla** [conda-forge/stack-feedstock#2]
Hey, I just updated the version number and the checksums of the recipe,
but my pull request fails with a CircleCI error message which I is unclear to me.
The Travis builds are all suceeding.
Can somebody help?
Here is the end of the [error-message](https://circleci.com/gh/conda-forge/stack-feedstock/8):

```
Using Anaconda API: https://api.anaconda.org
Traceback (most recent call last):
  File "/feedstock_root/ci_support/upload_or_check_non_existence.py", line 124, in <module>
    main()
  File "/feedstock_root/ci_support/upload_or_check_non_existence.py", line 106, in main
    on_channel = distribution_exists_on_channel(cli, meta, owner, channel)
  File "/feedstock_root/ci_support/upload_or_check_non_existence.py", line 69, in distribution_exists_on_channel
    binstar_cli.show_channel(owner=owner, channel=channel)['files']]
  File "/opt/conda/lib/python3.5/site-packages/binstar_client/mixins/channels.py", line 29, in     show_channel
    self._check_response(res, [200])
  File "/opt/conda/lib/python3.5/site-packages/binstar_client/__init__.py", line 200, in _check_response
    raise ErrCls(msg, res.status_code)
binstar_client.errors.ServerError: ('Bad Gateway: Invalid responses from another server/proxy. ([GET] https://api.anaconda.org/channels/conda-forge/main -> 502)', 502)

./ci_support/run_docker_build.sh returned exit code 1 
```

**Comment by eggzilla** [comment]
Ok, there are currently DNS problems with anaconda.org.
I found out by checking [conda-forge status](https://conda-forge.github.io/status/)
Will just sit it out.
